POST http://localhost:8080/users
content-type: application/json

{
    "telegramId": "212",
    "username": "lysmi"
}
###
GET  http://localhost:8080/users

###
GET http://localhost:8080/servers
###
POST http://localhost:8080/servers
content-type: application/json

{
    "ip": "0.0.0.0",
    "serverName": "lysmiServer"
}
  //   "serverName": "lysmiServer",
###
