POST http://192.168.255.13:8080/users
content-type: application/json

{
    "telegramId": "212",
    "username": "lysmi"
}
###
POST http://localhost:8080/users
content-type: application/json

{
    "telegramId": "212",
    "username": "lysmi"
}
###
GET  http://192.168.255.13:8080/users
###
GET  http://localhost:8080/users
###
GET  http://localhost:8080/users/byTelegramId/212
###
GET  http://192.168.255.13:8080/users/byTelegramId/212
###
GET http://localhost:8080/users/9945f805-b8aa-4d1d-a6d6-6fc2e68058d3
###
GET http://localhost:8080/users/772c7c27-564a-40f4-94f8-8179f536089d/qrCode
###
PATCH  http://192.168.255.13:8080/users/9590774f-7f1c-44a8-b288-31b2ba7feb11/addToBalance/55
###
PATCH  http://localhost:8080/users/9945f805-b8aa-4d1d-a6d6-6fc2e68058d3/useFreePeriod
###
GET http://192.168.255.13:8080/servers
###
POST http://192.168.255.13:8080/servers
content-type: application/json

{
    "ip": "139.59.130.218",
    "serverName": "lysmiServer"
}
  //   "serverName": "lysmiServer",
###
POST http://localhost:8080/servers
content-type: application/json

{
    "ip": "139.59.130.218",
    "serverName": "lysmiServer"
}
  //   "serverName": "lysmiServer",
###

GET http://139.59.130.218:8383/v1/devices/wg0/peers/ZX-G9X9oxyj3uw4PaTAZHd0R0n5taPKP3LzwH44SRW4=/quick.conf.png
Content-Type: application/json
Authorization: Bearer capybara
###

POST http://139.59.130.218:8383/v1/devices/wg0/peers/
Content-Type: application/json
Authorization: Bearer capybara

{
    "allowed_ips": ["10.10.1.1/32"]
}